import type { Metadata } from 'next'
import './globals.css'

import { Poppins } from 'next/font/google'
import Navbar from './components/Navbar'

const poppins = Poppins({
	weight: ['100', '300', '500', '600', '700', '800'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body className={poppins.className}>
				<Navbar />
				{children}
			</body>
		</html>
	)
}
